name: hy_goods2
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0<3.0.0"



dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  dio: ^4.0.6
  flutter_screenutil: ^5.6.1
  # string_num_calculate: ^0.0.3
  flutter_easy_permission: ^1.1.2
  flutter_scankit: ^1.2.4
  syncfusion_flutter_datagrid: ^20.4.49
  syncfusion_flutter_charts: ^20.4.50
  syncfusion_flutter_datepicker: ^20.4.53
  # flutter_cupertino_localizations: ^1.0.1
  syncfusion_flutter_treemap: ^20.4.53-beta
  # flutter_echarts: ^2.4.0
  # math_parser: ^1.5.0
  expression_language: ^1.0.1
  date_format: ^2.0.7
  flutter_staggered_grid_view: ^0.6.2

  #回头看下是否可以使用dio
  http: ^0.13.5   
  flutter_datetime_picker: ^1.5.1
  # date_time_picker: ^2.1.0
  syncfusion_localizations: ^20.4.53
  shared_preferences: ^2.0.6
  path_provider: ^2.0.14
  sqflite: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
